version: "3" 
services:
  service1:
    image: service1:latest
    ports:
      - "3000:3000"
  service2:
    image: service2:latest
    ports:
      - "3001:3001"
  service3:
    image: service3:latest
    ports:
      - "3002:3002"
