version: "3" 
services:
  service1:
    image: service1:latest
    build: ./service1
  service2:
    image: service2:latest
    build: ./service2
  service3:
    image: service3:latest
    build: ./service3